CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
   name VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   registration_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   uuid UUID NOT NULL,
   player_state_id BIGINT,
   profile_data_id BIGINT,
   CONSTRAINT accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE inventory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   count INTEGER NOT NULL,
   item_id INTEGER NOT NULL,
   meta INTEGER NOT NULL,
   slot INTEGER NOT NULL,
   player_state_id BIGINT NOT NULL,
   CONSTRAINT inventory_items_pkey PRIMARY KEY (id)
);

CREATE TABLE login_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
   address VARCHAR(255) NOT NULL,
   client_id BIGINT,
   client_uuid UUID,
   current_input_mode INTEGER,
   datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   default_input_mode INTEGER,
   device_id VARCHAR(255),
   device_model VARCHAR(255),
   device_os INTEGER,
   game_version VARCHAR(255),
   gui_scale INTEGER,
   identity_public_key VARCHAR(255),
   language_code VARCHAR(255),
   server_address VARCHAR(255),
   uuid UUID NOT NULL,
   username VARCHAR(255),
   xuid VARCHAR(255),
   account_id BIGINT NOT NULL,
   CONSTRAINT login_history_pkey PRIMARY KEY (id)
);

CREATE TABLE player_effects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   ambient BOOLEAN NOT NULL,
   amplifier INTEGER NOT NULL,
   duration INTEGER NOT NULL,
   effect_id INTEGER NOT NULL,
   visible BOOLEAN NOT NULL,
   player_state_id BIGINT NOT NULL,
   CONSTRAINT player_effects_pkey PRIMARY KEY (id)
);

CREATE TABLE player_state (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
   experience INTEGER NOT NULL,
   experience_level INTEGER NOT NULL,
   food_level INTEGER NOT NULL,
   head_yaw FLOAT8 NOT NULL,
   health FLOAT4 NOT NULL,
   held_item_index INTEGER NOT NULL,
   level_name VARCHAR(255) NOT NULL,
   max_health INTEGER NOT NULL,
   pitch FLOAT8 NOT NULL,
   saturation_level FLOAT4 NOT NULL,
   x FLOAT8 NOT NULL,
   y FLOAT8 NOT NULL,
   yaw FLOAT8 NOT NULL,
   z FLOAT8 NOT NULL,
   CONSTRAINT player_state_pkey PRIMARY KEY (id)
);

CREATE TABLE profile_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
   age INTEGER NOT NULL,
   sex VARCHAR(255) NOT NULL,
   CONSTRAINT profile_data_pkey PRIMARY KEY (id)
);

ALTER TABLE accounts ADD CONSTRAINT uk_22fvt0prnafepjuqjhs2da68e UNIQUE (name);

ALTER TABLE accounts ADD CONSTRAINT uk_k9t0w9mnf8iele77rvjoqynsd UNIQUE (profile_data_id);

ALTER TABLE accounts ADD CONSTRAINT uk_orinnbp409m9i70p4mvttidm0 UNIQUE (player_state_id);

ALTER TABLE inventory_items ADD CONSTRAINT fk8rqvxkqmdw0jvxuesj4bsouuw FOREIGN KEY (player_state_id) REFERENCES player_state (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE player_effects ADD CONSTRAINT fkdid6tc0l7gsugptfs93jut2c2 FOREIGN KEY (player_state_id) REFERENCES player_state (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE accounts ADD CONSTRAINT fkhdhf0w7xtbhwi2b6fn50pwl7w FOREIGN KEY (profile_data_id) REFERENCES profile_data (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE accounts ADD CONSTRAINT fkll8ro0vkfudow7yopdjtvrdoc FOREIGN KEY (player_state_id) REFERENCES player_state (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE login_history ADD CONSTRAINT fkp5tfdafm0bnheeplrrv8v0c69 FOREIGN KEY (account_id) REFERENCES accounts (id) ON UPDATE NO ACTION ON DELETE NO ACTION;